# model_data.py

MODEL_DEFINITIONS = {
  "invoice": [
    {"display": "発行日", "value": "issue_date"},
    {"display": "利用月", "value": "issue_month"},
    {"display": "請求書番号", "value": "invoice_number"},
    {"display": "タイトル", "value": "title"},
    {"display": "ページ番号", "value": "page_number"},
    {"display": "請求元会社名", "value": "biller_company"},
    {"display": "請求元住所", "value": "biller_address"},
    {"display": "登録番号", "value": "register_no"},
    {"display": "請求元TEL", "value": "biller_tel"},
    {"display": "請求元FAX", "value": "biller_fax"},
    {"display": "請求先会社名", "value": "billing_company"},
    {"display": "請求先部署名", "value": "office_name"},
    {"display": "通貨", "value": "currency"},
    {"display": "合計金額税抜", "value": "subtotal"},
    {"display": "8%対象合計額", "value": "reduced_subtotal"},
    {"display": "10%対象合計額", "value": "non_reduced_subtotal"},
    {"display": "合計金額税込", "value": "total_amount"},
    {"display": "消費税", "value": "consumption_tax"},
    {"display": "税額10%", "value": "non_reduced_tax"},
    {"display": "税額8%", "value": "reduced_tax"},
    {"display": "支払期限", "value": "due_date"},
    {"display": "銀行名", "value": "bank_name"},
    {"display": "支店名", "value": "bankbranch_name"},
    {"display": "口座種別", "value": "account_type"},
    {"display": "口座番号", "value": "account_number"},
    {"display": "口座名義", "value": "account_name"},
    {"display": "明細/No.", "value": "invoice_table_number"},
    {"display": "明細/品名", "value": "invoice_table_item_name"},
    {"display": "明細/数量", "value": "invoice_table_quantity"},
    {"display": "明細/単価", "value": "invoice_table_unit_price"},
    {"display": "明細/金額", "value": "invoice_table_amount"},
    {"display": "明細/備考", "value": "invoice_table_remarks"}
  ],
  "receipt": [
    {"display": "タイトル", "value": "title"},
    {"display": "発行日", "value": "issue_date"},
    {"display": "発行時刻", "value": "issue_time"},
    {"display": "合計金額税込", "value": "total_amount"},
    {"display": "合計金額税抜", "value": "subtotal"},
    {"display": "消費税", "value": "consumption_tax"},
    {"display": "税額10%", "value": "non_reduced_tax"},
    {"display": "税額8%", "value": "reduced_tax"},
    {"display": "支払者会社名", "value": "billing_company"},
    {"display": "支払者部署名", "value": "office_name"},
    {"display": "発行者会社名", "value": "biller_company"},
    {"display": "発行者TEL", "value": "biller_tel"},
    {"display": "発行者住所", "value": "biller_address"},
    {"display": "発行者部署名", "value": "biller_office_name"}
  ],
  "purchase_order": [
    {"display": "注文先会社名", "value": "seller_company"},
    {"display": "注文先部署名", "value": "seller_division"},
    {"display": "注文先担当者名", "value": "seller_name"},
    {"display": "注文書番号", "value": "buyer_ordernumber"},
    {"display": "注文日", "value": "buyer_date"},
    {"display": "発行元会社名", "value": "buyer_company"},
    {"display": "発行元部署名", "value": "buyer_division"},
    {"display": "発行元住所", "value": "buyer_address"},
    {"display": "発行元電話番号", "value": "buyer_phonenumber"},
    {"display": "発行元FAX番号", "value": "buyer_faxnumber"},
    {"display": "発行元担当者名", "value": "buyer_name"},
    {"display": "合計金額", "value": "buyer_totalamount"},
    {"display": "備考", "value": "remarks"},
    {"display": "希望納期", "value": "receiver_deliverydate"},
    {"display": "納品先住所", "value": "receiver_address"},
    {"display": "納品先電話番号", "value": "receiver_phonenumber"},
    {"display": "納品先FAX番号", "value": "receiver_faxnumber"},
    {"display": "納品先担当者名", "value": "receiver_name"},
    {"display": "明細/No.", "value": "purchase_order_table_number"},
    {"display": "明細/注文番号", "value": "purchase_order_table_order_number"},
    {"display": "明細/品番", "value": "purchase_order_table_item_number"},
    {"display": "明細/品名", "value": "purchase_order_table_item_name"},
    {"display": "明細/数量", "value": "purchase_order_table_quantity"},
    {"display": "明細/単価", "value": "purchase_order_table_unit_price"},
    {"display": "明細/金額", "value": "purchase_order_table_amount"},
    {"display": "明細/備考", "value": "purchase_order_table_remarks"}
  ]
}